#!/usr/bin/python2.7

import dbus
import avahi

serviceName = "ISCSI Service"
serviceType = "_iscsi-target._tcp" # See http://www.dns-sd.org/ServiceTypes.html
servicePort = 3260
serviceTXT = "/dev/sda" #TXT record for the service

domain = "" # Domain to publish on, default to .local
host = "" # Host to publish records for, default to localhost

group = None #our entry group
rename_count = 12 # Counter so we only rename after collisions a sensible number of times

def add_service():
	global group, serviceName, serviceType, servicePort, serviceTXT, domain, host
	if group is None:
		group = dbus.Interface(
				bus.get_object( avahi.DBUS_NAME, server.EntryGroupNew()),
				avahi.DBUS_INTERFACE_ENTRY_GROUP)

	print "Adding service '%s' of type '%s' ..." % (serviceName, serviceType)

	group.AddService(
			avahi.IF_UNSPEC,	#interface
			avahi.PROTO_UNSPEC, #protocol
			dbus.UInt32(0), #flags
			serviceName, serviceType,
			domain, host,
			dbus.UInt16(servicePort),
			serviceTXT)
	group.Commit()

def remove_service():
	global group

	if not group is None:
		group.Reset()

if __name__ == '__main__':
	bus = dbus.SystemBus()

	server = dbus.Interface(
			bus.get_object( avahi.DBUS_NAME, avahi.DBUS_PATH_SERVER ),
			avahi.DBUS_INTERFACE_SERVER )

	add_service()

	if not group is None:
		group.Free()
